# Generated by Django 2.2 on 2020-03-14 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(default=1, upload_to='', verbose_name='Файл'),
            preserve_default=False,
        ),
    ]
