# Generated by Django 2.2 on 2020-03-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20200314_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='access',
            field=models.CharField(choices=[('free', 'Общий'), ('hidden', 'Скрытый'), ('private', 'Приватный')], default='free', max_length=20, verbose_name='Доступ'),
        ),
    ]
