# Generated by Django 2.2 on 2020-03-14 11:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0004_file_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='private',
            field=models.ManyToManyField(blank=True, related_name='private_files', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи'),
        ),
    ]
